name: CMake_new

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  code_analysis:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2

    - run: sudo apt-get update -yq
    - run: sudo apt-get install -yq clang clang-tidy cppcheck iwyu

    - name: clang tests
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTEST_CLANG=true -DTEST_CPPCHECK=false -DTEST_IWYU=false ${{github.workspace}}
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Cppcheck tests
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTEST_CLANG=false -DTEST_CPPCHECK=true -DTEST_IWYU=false ${{github.workspace}}
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: IWYU tests
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTEST_CLANG=false -DTEST_CPPCHECK=false -DTEST_IWYU=true ${{github.workspace}}
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
