name: CMake_codechecker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  CodeChecker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update -yq
    - run: sudo apt-get install -yq clang clang-tidy cppcheck iwyu 
    - run: sudo snap install codechecker --classic

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{github.workspace}}

    - name: Build
      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}}
      
    - name: CodeChecker
      run: make codechecker
